# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb3949b9306e57a8be6418b8fc54e2e5b7aecc20344c7d4fb0dbe85cf79ea2adbe517a73240bd67ed71a5556bef10c9cf049ba117c0a498afe8d2510423ed77c

test:
  secret_key_base: f735b3c352908c74731644968d462db9bf20124a0bafadfd19e7d3ac70ac2a11ea0c9d1ce2399faf903e9e9b58d5846257d85d3bfb57da9cd888969b114af027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
